name: Ladder
author: DerBanko
version: 1.0
main: tv.banko.ladder.Ladder
api-version: 1.16
description: Event on the 1st of July, 2022

depend:
  - EventCore

commands:
  ladder:
    description: Show your ladder
    aliases: [ l ]